# Generated by Django 2.2.18 on 2021-06-09 10:09

import apps.doctors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=3000)),
                ('phone_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('desc', models.CharField(max_length=2500)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=apps.doctors.models.login_thumbmail_path)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('hos_name', models.CharField(max_length=100)),
                ('spec', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('experience', models.CharField(max_length=3000)),
                ('phone_no', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('time', models.CharField(max_length=250)),
                ('thumbnail', models.FileField(blank=True, null=True, upload_to=apps.doctors.models.edit_thumbmail_path)),
            ],
        ),
    ]
